# Generated by Django 3.0.5 on 2020-09-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20200908_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mainimg',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
